import React, { createContext, useContext, useState, useCallback } from 'react';

const translations = {
  sk: {
    nav: { home: 'Domov', about: 'O nás', projects: 'Realizácie', services: 'Služby', contact: 'Kontakt', consultation: 'Konzultácia' },
    services_menu: { kitchens: 'Kuchyne', wardrobes: 'Skrine', tables: 'Stoly', doors: 'Dvere', custom: 'Nábytok na mieru' },
    hero: { title_top: 'VAŠE PREDSTAVY,', title_bottom: 'NAŠA PRECÍZNOSŤ', subtitle: 'Vyrábame interiéry na mieru, ktoré zdvíhajú váš štýl a pohodlie.', cta: 'Pozrieť realizácie' },
    about: { label: 'O NÁS', title: 'Daniel Kubin', subtitle: 'STOLÁRSTVO', description: '15 rokov skúseností s výrobou kvalitného nábytku na mieru. Naša vášeň pre drevo a precíznosť sa odráža v každom projekte.', mission_title: 'Naša filozofia', mission: 'Veríme, že kvalitný nábytok je investícia, nie výdavok. Každý kúsok vyrábame s maximálnou precíznosťou z overených materiálov.', experience: 'Rokov skúseností', projects_done: 'Dokončených projektov', clients: 'Spokojných klientov', materials: 'Premium materiálov', team_label: 'TÍM', team_title: 'Ľudia za každým projektom', team_subtitle: 'Náš tím odborníkov sa stará o každý detail – od prvého návrhu po finálnu montáž.' },
    projects: { label: 'PORTFÓLIO', title: 'Naše projekty', subtitle: 'Každý projekt je unikátny príbeh o precíznosti a materiáloch.', all: 'Všetko', kitchens: 'Kuchyne', wardrobes: 'Skrine', tables: 'Stoly', doors: 'Dvere', furniture: 'Nábytok', location: 'Lokácia', year: 'Rok', materials_used: 'Použité materiály', description: 'Popis projektu', gallery: 'Galéria projektu', interested: 'Máte záujem o podobný projekt?', interested_desc: 'Kontaktujte nás pre nezáväznú konzultáciu', contact_us: 'Nezáväzná konzultácia', clientGoals: 'Ciele klienta', process: 'Postup realizácie', challenges: 'Výzvy projektu', customSolutions: 'Vlastné riešenia', technicalDetails: 'Technické detaily' },
    process: { label: 'AKO PRACUJEME', title: 'Od návrhu po realizáciu v 4 krokoch', step1_title: 'Konzultácia', step1_desc: 'Stretneme sa u vás doma, vypočujeme vaše predstavy a zameriame priestor. Bezplatná a nezáväzná.', step2_title: 'Návrh & 3D', step2_desc: 'Pripravíme návrh vrátane 3D vizualizácie. Uvidíte výsledok ešte pred začatím výroby.', step3_title: 'Výroba', step3_desc: 'Vyrábame s maximálnou presnosťou z kvalitných materiálov od overených dodávateľov.', step4_title: 'Montáž', step4_desc: 'Profesionálna montáž priamo u vás. Po dokončení všetko upraceme a odovzdávame v perfektnom stave.' },
    testimonials: { label: 'REFERENCIE', title: 'Čo hovoria naši klienti' },
    cta: { title: 'Máte záujem o podobný projekt?', subtitle: 'Radi vám pomôžeme s realizáciou vašich predstáv.', button: 'Nezáväzná konzultácia' },
    contact: { label: 'KONTAKT', title: 'Kontaktujte nás', subtitle: 'Radi vám odpovieme na všetky otázky a dohodneme si termín bezplatnej konzultácie.', name: 'Meno a priezvisko', email: 'E-mail', phone: 'Telefón', message: 'Správa', send: 'Odoslať správu', address: 'Adresa', office_hours: 'Pracovná doba', mon_fri: 'Po - Pi', sat: 'Sobota', closed: 'Zatvorené' },
    footer: { rights: 'Všetky práva vyhradené', privacy: 'Ochrana súkromia', terms: 'Obchodné podmienky' },
    services_page: { label: 'SLUŽBY', subtitle: 'Ponúkame komplexné riešenia pre váš interiér – od návrhu až po montáž.', about_label: 'O tejto službe', kitchens_title: 'Kuchyne na mieru', wardrobes_title: 'Skrine a šatníky', tables_title: 'Stoly', doors_title: 'Dvere', custom_title: 'Nábytok na mieru', kitchens_desc: 'Navrhujeme a vyrábame moderné kuchyne, ktoré sú funkčné aj estetické. Každá kuchyňa je unikátna a vyrábame ju presne podľa vašich predstáv a rozmerov priestoru.', wardrobes_desc: 'Šatníky a vstavaný nábytok navrhnutý presne podľa vašich potrieb a priestoru. Riešime úložné priestory efektívne a so štýlom.', tables_desc: 'Ručne vyrábané stoly z masívneho dreva. Každý kus je originál s unikátnou kresbou dreva.', doors_desc: 'Interiérové dvere na mieru, ktoré dotvoria charakter vášho priestoru. Vyrábame so skrytými pántmi aj viditeľnými.', custom_desc: 'Akýkoľvek nábytok podľa vašich predstáv. Od knižníc po TV steny. Špeciálne riešenia pre každý priestor.', kitchens_materials: ['Masívny dub', 'Orech americký', 'MDF lak', 'Mramor', 'Granit', 'Mosadzné úchytky', 'LED osvetlenie'], wardrobes_materials: ['Orech americký', 'Dub prírodný', 'Zrkadlové sklo', 'LED osvetlenie', 'Hliníkové profily'], tables_materials: ['Masívny dub', 'Masívny orech', 'Oceľové nohy', 'Prírodný olej', 'Epoxidová živica'], doors_materials: ['Orech americký', 'Masívny dub', 'Skryté pánty', 'Magnetické zámky', 'Prírodný olej'], custom_materials: ['Orech americký', 'Masívny dub', 'Sklo', 'Kov', 'LED pásy', 'Mosadzné prvky'] }
  },
  cz: {
    nav: { home: 'Domů', about: 'O nás', projects: 'Realizace', services: 'Služby', contact: 'Kontakt', consultation: 'Konzultace' },
    services_menu: { kitchens: 'Kuchyně', wardrobes: 'Skříně', tables: 'Stoly', doors: 'Dveře', custom: 'Nábytek na míru' },
    hero: { title_top: 'VAŠE PŘEDSTAVY,', title_bottom: 'NAŠE PRECIZNOST', subtitle: 'Vyrábíme interiéry na míru, které pozvednou váš styl a pohodlí.', cta: 'Zobrazit realizace' },
    about: { label: 'O NÁS', title: 'Daniel Kubin', subtitle: 'TRUHLÁŘSTVÍ', description: '15 let zkušeností s výrobou kvalitního nábytku na míru. Naše vášeň pro dřevo a preciznost se odráží v každém projektu.', mission_title: 'Naše filozofie', mission: 'Věříme, že kvalitní nábytek je investice, ne výdaj. Každý kus vyrábíme s maximální precizností z ověřených materiálů.', experience: 'Let zkušeností', projects_done: 'Dokončených projektů', clients: 'Spokojených klientů', materials: 'Premium materiálů', team_label: 'TÝM', team_title: 'Lidé za každým projektem', team_subtitle: 'Náš tým odborníků se stará o každý detail – od prvního návrhu po finální montáž.' },
    projects: { label: 'PORTFÓLIO', title: 'Naše projekty', subtitle: 'Každý projekt je jedinečný příběh o preciznosti a materiálech.', all: 'Vše', kitchens: 'Kuchyně', wardrobes: 'Skříně', tables: 'Stoly', doors: 'Dveře', furniture: 'Nábytek', location: 'Lokace', year: 'Rok', materials_used: 'Použité materiály', description: 'Popis projektu', gallery: 'Galerie projektu', interested: 'Máte zájem o podobný projekt?', interested_desc: 'Kontaktujte nás pro nezávaznou konzultaci', contact_us: 'Nezávazná konzultace', clientGoals: 'Cíle klienta', process: 'Postup realizace', challenges: 'Výzvy projektu', customSolutions: 'Vlastní řešení', technicalDetails: 'Technické detaily' },
    process: { label: 'JAK PRACUJEME', title: 'Od návrhu po realizaci ve 4 krocích', step1_title: 'Konzultace', step1_desc: 'Setkáme se u vás doma, vyslechneme vaše představy a zaměříme prostor. Bezplatná a nezávazná.', step2_title: 'Návrh & 3D', step2_desc: 'Připravíme návrh včetně 3D vizualizace. Uvidíte výsledek ještě před začátkem výroby.', step3_title: 'Výroba', step3_desc: 'Vyrábíme s maximální přesností z kvalitních materiálů od ověřených dodavatelů.', step4_title: 'Montáž', step4_desc: 'Profesionální montáž přímo u vás. Po dokončení vše uklidíme a předáváme v perfektním stavu.' },
    testimonials: { label: 'REFERENCE', title: 'Co říkají naši klienti' },
    cta: { title: 'Máte zájem o podobný projekt?', subtitle: 'Rádi vám pomůžeme s realizací vašich představ.', button: 'Nezávazná konzultace' },
    contact: { label: 'KONTAKT', title: 'Kontaktujte nás', subtitle: 'Rádi odpovíme na všechny vaše dotazy a domluvíme termín bezplatné konzultace.', name: 'Jméno a příjmení', email: 'E-mail', phone: 'Telefon', message: 'Zpráva', send: 'Odeslat zprávu', address: 'Adresa', office_hours: 'Pracovní doba', mon_fri: 'Po - Pá', sat: 'Sobota', closed: 'Zavřeno' },
    footer: { rights: 'Všechna práva vyhrazena', privacy: 'Ochrana soukromí', terms: 'Obchodní podmínky' },
    services_page: { label: 'SLUŽBY', subtitle: 'Nabízíme komplexní řešení pro váš interiér – od návrhu až po montáž.', about_label: 'O této službě', kitchens_title: 'Kuchyně na míru', wardrobes_title: 'Skříně a šatny', tables_title: 'Stoly', doors_title: 'Dveře', custom_title: 'Nábytek na míru', kitchens_desc: 'Navrhujeme a vyrábíme moderní kuchyně, které jsou funkční i estetické. Každá kuchyně je jedinečná a vyrábíme ji přesně podle vašich představ.', wardrobes_desc: 'Šatny a vestavěný nábytek navržený přesně podle vašich potřeb. Efektivní a stylová úložná řešení.', tables_desc: 'Ručně vyráběné stoly z masivního dřeva. Každý kus je originál s unikátní kresbou dřeva.', doors_desc: 'Interiérové dveře na míru, které dotvoří charakter vašeho prostoru. Vyrábíme se skrytými i viditelnými panty.', custom_desc: 'Jakýkoliv nábytek podle vašich představ. Od knihoven po TV stěny. Speciální řešení pro každý prostor.', kitchens_materials: ['Masivní dub', 'Ořech americký', 'MDF lak', 'Mramor', 'Granit', 'Mosazné úchytky', 'LED osvětlení'], wardrobes_materials: ['Ořech americký', 'Dub přírodní', 'Zrcadlové sklo', 'LED osvětlení', 'Hliníkové profily'], tables_materials: ['Masivní dub', 'Masivní ořech', 'Ocelové nohy', 'Přírodní olej', 'Epoxidová pryskyřice'], doors_materials: ['Ořech americký', 'Masivní dub', 'Skryté panty', 'Magnetické zámky', 'Přírodní olej'], custom_materials: ['Ořech americký', 'Masivní dub', 'Sklo', 'Kov', 'LED pásky', 'Mosazné prvky'] }
  },
  de: {
    nav: { home: 'Startseite', about: 'Über uns', projects: 'Projekte', services: 'Leistungen', contact: 'Kontakt', consultation: 'Beratung' },
    services_menu: { kitchens: 'Küchen', wardrobes: 'Schränke', tables: 'Tische', doors: 'Türen', custom: 'Möbel nach Maß' },
    hero: { title_top: 'IHRE VORSTELLUNGEN,', title_bottom: 'UNSERE PRÄZISION', subtitle: 'Wir fertigen maßgeschneiderte Inneneinrichtungen, die Ihren Stil und Komfort erhöhen.', cta: 'Projekte ansehen' },
    about: { label: 'ÜBER UNS', title: 'Daniel Kubin', subtitle: 'TISCHLEREI', description: '15 Jahre Erfahrung in der Herstellung hochwertiger Maßmöbel. Unsere Leidenschaft für Holz und Präzision spiegelt sich in jedem Projekt wider.', mission_title: 'Unsere Philosophie', mission: 'Wir glauben, dass hochwertige Möbel eine Investition sind. Jedes Stück wird mit maximaler Präzision gefertigt.', experience: 'Jahre Erfahrung', projects_done: 'Abgeschlossene Projekte', clients: 'Zufriedene Kunden', materials: 'Premium-Materialien', team_label: 'TEAM', team_title: 'Die Menschen hinter jedem Projekt', team_subtitle: 'Unser Expertenteam kümmert sich um jedes Detail – vom ersten Entwurf bis zur finalen Montage.' },
    projects: { label: 'PORTFOLIO', title: 'Unsere Projekte', subtitle: 'Jedes Projekt ist eine einzigartige Geschichte über Präzision und Materialien.', all: 'Alle', kitchens: 'Küchen', wardrobes: 'Schränke', tables: 'Tische', doors: 'Türen', furniture: 'Möbel', location: 'Standort', year: 'Jahr', materials_used: 'Verwendete Materialien', description: 'Projektbeschreibung', gallery: 'Projektgalerie', interested: 'Interesse an einem ähnlichen Projekt?', interested_desc: 'Kontaktieren Sie uns für eine unverbindliche Beratung', contact_us: 'Unverbindliche Beratung', clientGoals: 'Kundenziele', process: 'Realisierungsablauf', challenges: 'Projektherausforderungen', customSolutions: 'Individuelle Lösungen', technicalDetails: 'Technische Details' },
    process: { label: 'UNSER PROZESS', title: 'Vom Entwurf zur Realisierung in 4 Schritten', step1_title: 'Beratung', step1_desc: 'Wir treffen uns bei Ihnen zu Hause, hören Ihre Vorstellungen und vermessen den Raum.', step2_title: 'Entwurf & 3D', step2_desc: 'Wir erstellen einen Entwurf inkl. 3D-Visualisierung.', step3_title: 'Fertigung', step3_desc: 'Wir fertigen mit maximaler Präzision aus hochwertigen Materialien.', step4_title: 'Montage', step4_desc: 'Professionelle Montage direkt bei Ihnen. Alles wird perfekt übergeben.' },
    testimonials: { label: 'REFERENZEN', title: 'Was unsere Kunden sagen' },
    cta: { title: 'Interesse an einem ähnlichen Projekt?', subtitle: 'Wir helfen Ihnen gerne bei der Umsetzung Ihrer Vorstellungen.', button: 'Unverbindliche Beratung' },
    contact: { label: 'KONTAKT', title: 'Kontaktieren Sie uns', subtitle: 'Wir beantworten gerne alle Ihre Fragen und vereinbaren einen Termin für eine kostenlose Beratung.', name: 'Vor- und Nachname', email: 'E-Mail', phone: 'Telefon', message: 'Nachricht', send: 'Nachricht senden', address: 'Adresse', office_hours: 'Öffnungszeiten', mon_fri: 'Mo - Fr', sat: 'Samstag', closed: 'Geschlossen' },
    footer: { rights: 'Alle Rechte vorbehalten', privacy: 'Datenschutz', terms: 'AGB' },
    services_page: { label: 'LEISTUNGEN', subtitle: 'Wir bieten umfassende Lösungen für Ihr Interieur – von der Planung bis zur Montage.', about_label: 'Über diese Leistung', kitchens_title: 'Küchen nach Maß', wardrobes_title: 'Schränke & Garderoben', tables_title: 'Tische', doors_title: 'Türen', custom_title: 'Möbel nach Maß', kitchens_desc: 'Wir entwerfen und fertigen moderne Küchen, die funktional und ästhetisch sind. Jede Küche ist einzigartig und wird genau nach Ihren Vorstellungen gefertigt.', wardrobes_desc: 'Garderoben und Einbaumöbel, genau nach Ihren Bedürfnissen. Effiziente und stilvolle Stauraumlösungen.', tables_desc: 'Handgefertigte Tische aus Massivholz. Jedes Stück ist ein Original mit einzigartiger Holzmaserung.', doors_desc: 'Innentüren nach Maß, die den Charakter Ihres Raumes vervollständigen.', custom_desc: 'Jedes Möbelstück nach Ihren Vorstellungen. Von Bücherregalen bis TV-Wänden.', kitchens_materials: ['Massiveiche', 'Amerikanischer Nussbaum', 'MDF-Lack', 'Marmor', 'Granit', 'Messinggriffe', 'LED-Beleuchtung'], wardrobes_materials: ['Amerikanischer Nussbaum', 'Natürliche Eiche', 'Spiegelglas', 'LED-Beleuchtung', 'Aluminiumprofile'], tables_materials: ['Massiveiche', 'Massiver Nussbaum', 'Stahlbeine', 'Naturöl', 'Epoxidharz'], doors_materials: ['Amerikanischer Nussbaum', 'Massiveiche', 'Verdeckte Scharniere', 'Magnetschloss', 'Naturöl'], custom_materials: ['Amerikanischer Nussbaum', 'Massiveiche', 'Glas', 'Metall', 'LED-Streifen', 'Messingelemente'] }
  },
  en: {
    nav: { home: 'Home', about: 'About', projects: 'Projects', services: 'Services', contact: 'Contact', consultation: 'Consultation' },
    services_menu: { kitchens: 'Kitchens', wardrobes: 'Wardrobes', tables: 'Tables', doors: 'Doors', custom: 'Custom Furniture' },
    hero: { title_top: 'YOUR VISION,', title_bottom: 'OUR PRECISION', subtitle: 'We craft bespoke interiors that elevate your style and comfort.', cta: 'View Projects' },
    about: { label: 'ABOUT US', title: 'Daniel Kubin', subtitle: 'CARPENTRY', description: '15 years of experience crafting premium custom furniture. Our passion for wood and precision is reflected in every project.', mission_title: 'Our Philosophy', mission: 'We believe quality furniture is an investment, not an expense. Every piece is crafted with maximum precision from verified materials.', experience: 'Years of Experience', projects_done: 'Completed Projects', clients: 'Happy Clients', materials: 'Premium Materials', team_label: 'TEAM', team_title: 'The People Behind Every Project', team_subtitle: 'Our team of experts takes care of every detail – from the first design to the final installation.' },
    projects: { label: 'PORTFOLIO', title: 'Our Projects', subtitle: 'Each project is a unique story of precision and materials.', all: 'All', kitchens: 'Kitchens', wardrobes: 'Wardrobes', tables: 'Tables', doors: 'Doors', furniture: 'Furniture', location: 'Location', year: 'Year', materials_used: 'Materials Used', description: 'Project Description', gallery: 'Project Gallery', interested: 'Interested in a similar project?', interested_desc: 'Contact us for a free consultation', contact_us: 'Free Consultation', clientGoals: 'Client Goals', process: 'Production Process', challenges: 'Project Challenges', customSolutions: 'Custom Solutions', technicalDetails: 'Technical Details' },
    process: { label: 'OUR PROCESS', title: 'From Design to Realization in 4 Steps', step1_title: 'Consultation', step1_desc: 'We visit your home, listen to your ideas, and measure the space. Free and non-binding.', step2_title: 'Design & 3D', step2_desc: 'We prepare a design including 3D visualization. See the result before production begins.', step3_title: 'Production', step3_desc: 'We manufacture with maximum precision from quality materials by verified suppliers.', step4_title: 'Installation', step4_desc: 'Professional installation at your place. Everything is cleaned and delivered in perfect condition.' },
    testimonials: { label: 'TESTIMONIALS', title: 'What Our Clients Say' },
    cta: { title: 'Interested in a similar project?', subtitle: 'We\'d love to help you realize your vision.', button: 'Free Consultation' },
    contact: { label: 'CONTACT', title: 'Contact Us', subtitle: 'We\'ll happily answer all your questions and schedule a free consultation.', name: 'Full Name', email: 'Email', phone: 'Phone', message: 'Message', send: 'Send Message', address: 'Address', office_hours: 'Office Hours', mon_fri: 'Mon - Fri', sat: 'Saturday', closed: 'Closed' },
    footer: { rights: 'All rights reserved', privacy: 'Privacy Policy', terms: 'Terms & Conditions' },
    services_page: { label: 'SERVICES', subtitle: 'We offer comprehensive interior solutions – from design to installation.', about_label: 'About This Service', kitchens_title: 'Custom Kitchens', wardrobes_title: 'Wardrobes & Closets', tables_title: 'Tables', doors_title: 'Doors', custom_title: 'Custom Furniture', kitchens_desc: 'We design and craft modern kitchens that are both functional and aesthetic. Every kitchen is unique and made exactly to your vision and space dimensions.', wardrobes_desc: 'Wardrobes and built-in furniture designed exactly to your needs and space. Efficient and stylish storage solutions.', tables_desc: 'Handcrafted tables from solid wood. Every piece is an original with a unique wood grain pattern.', doors_desc: 'Custom interior doors that complete the character of your space. We produce with hidden and visible hinges.', custom_desc: 'Any furniture according to your vision. From bookcases to TV walls. Special solutions for every space.', kitchens_materials: ['Solid Oak', 'American Walnut', 'MDF Lacquer', 'Marble', 'Granite', 'Brass Hardware', 'LED Lighting'], wardrobes_materials: ['American Walnut', 'Natural Oak', 'Mirror Glass', 'LED Lighting', 'Aluminum Profiles'], tables_materials: ['Solid Oak', 'Solid Walnut', 'Steel Legs', 'Natural Oil', 'Epoxy Resin'], doors_materials: ['American Walnut', 'Solid Oak', 'Hidden Hinges', 'Magnetic Locks', 'Natural Oil'], custom_materials: ['American Walnut', 'Solid Oak', 'Glass', 'Metal', 'LED Strips', 'Brass Elements'] }
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('sk');

  const t = useCallback((path) => {
    const keys = path.split('.');
    let result = translations[language];
    for (const key of keys) {
      result = result?.[key];
    }
    return result || path;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used inside LanguageProvider');
  return ctx;
}